version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: fizz
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: fizz
      MYSQL_CHARSET: utf8mb4
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql
